import '../models/user_model.dart';
import '../models/facility_model.dart';

class DummyData {
  // ============================================================
  // USERS
  // ============================================================
  static const List<UserModel> users = [
    UserModel(
      id: 'u001',
      name: 'Ahmad Fauzi',
      email: 'admin@fom.com',
      role: 'admin',
      department: 'Tim Operasional',
      avatar: 'AF',
    ),
    UserModel(
      id: 'u002',
      name: 'Sari Dewi',
      email: 'sari@fom.com',
      role: 'karyawan',
      department: 'Marketing',
      avatar: 'SD',
    ),
    UserModel(
      id: 'u003',
      name: 'Budi Santoso',
      email: 'budi@fom.com',
      role: 'karyawan',
      department: 'IT',
      avatar: 'BS',
    ),
  ];

  // Credential untuk login
  static const Map<String, String> credentials = {
    'admin@fom.com': 'admin123',
    'sari@fom.com': 'karyawan123',
    'budi@fom.com': 'karyawan123',
  };

  // ============================================================
  // GEDUNG DATA (with nested Lantai → Ruangan → Asset)
  // ============================================================
  static List<GedungModel> get gedungList => [
        GedungModel(
          id: 'g001',
          name: 'Gedung Utama',
          alamat: 'Jl. Sudirman No. 1, Jakarta Pusat',
          penanggungJawab: 'Ahmad Fauzi',
          totalLantai: 4,
          lantai: _lantaiGedungUtama,
        ),
        GedungModel(
          id: 'g002',
          name: 'Gedung Annex',
          alamat: 'Jl. Sudirman No. 3, Jakarta Pusat',
          penanggungJawab: 'Ahmad Fauzi',
          totalLantai: 2,
          lantai: _lantaiGedungAnnex,
        ),
      ];

  static List<LantaiModel> get _lantaiGedungUtama => [
        LantaiModel(
          id: 'l001',
          name: 'Lantai 1',
          nomorLantai: 1,
          gedungId: 'g001',
          ruangan: [
            RuanganModel(
              id: 'r001',
              name: 'Ruang Meeting A',
              lantaiId: 'l001',
              kapasitas: 20,
              tipe: 'Ruang Rapat',
              assets: [
                AssetModel(
                  id: 'a001',
                  name: 'AC Daikin 2PK',
                  category: 'AC',
                  status: AssetStatus.baik,
                  ruanganId: 'r001',
                  lastMaintenance: DateTime(2025, 3, 10),
                  serialNumber: 'DAI-2024-001',
                  brand: 'Daikin',
                  kondisi: '90%',
                ),
                AssetModel(
                  id: 'a002',
                  name: 'Proyektor Epson EB-X41',
                  category: 'Proyektor',
                  status: AssetStatus.baik,
                  ruanganId: 'r001',
                  lastMaintenance: DateTime(2025, 2, 15),
                  serialNumber: 'EPS-2023-012',
                  brand: 'Epson',
                  kondisi: '85%',
                ),
                AssetModel(
                  id: 'a003',
                  name: 'Smart TV Samsung 55"',
                  category: 'Smart TV',
                  status: AssetStatus.maintenance,
                  ruanganId: 'r001',
                  lastMaintenance: DateTime(2025, 1, 20),
                  serialNumber: 'SAM-2022-003',
                  brand: 'Samsung',
                  kondisi: '70%',
                ),
              ],
            ),
            RuanganModel(
              id: 'r002',
              name: 'Ruang Meeting B',
              lantaiId: 'l001',
              kapasitas: 10,
              tipe: 'Ruang Rapat',
              assets: [
                AssetModel(
                  id: 'a004',
                  name: 'AC LG Dual Cool',
                  category: 'AC',
                  status: AssetStatus.baik,
                  ruanganId: 'r002',
                  lastMaintenance: DateTime(2025, 4, 5),
                  serialNumber: 'LG-2024-007',
                  brand: 'LG',
                  kondisi: '95%',
                ),
                AssetModel(
                  id: 'a005',
                  name: 'Whiteboard Besar',
                  category: 'Furniture',
                  status: AssetStatus.baik,
                  ruanganId: 'r002',
                  lastMaintenance: DateTime(2024, 12, 1),
                  serialNumber: 'WB-2021-002',
                  brand: 'Local',
                  kondisi: '80%',
                ),
              ],
            ),
            RuanganModel(
              id: 'r003',
              name: 'Lobby Utama',
              lantaiId: 'l001',
              kapasitas: 50,
              tipe: 'Lobby',
              assets: [
                AssetModel(
                  id: 'a006',
                  name: 'CCTV Hikvision',
                  category: 'CCTV',
                  status: AssetStatus.baik,
                  ruanganId: 'r003',
                  lastMaintenance: DateTime(2025, 5, 1),
                  serialNumber: 'HIK-2024-015',
                  brand: 'Hikvision',
                  kondisi: '98%',
                ),
                AssetModel(
                  id: 'a007',
                  name: 'Lampu LED Panel',
                  category: 'Lampu',
                  status: AssetStatus.rusak,
                  ruanganId: 'r003',
                  lastMaintenance: DateTime(2024, 11, 10),
                  serialNumber: 'LED-2022-020',
                  brand: 'Philips',
                  kondisi: '40%',
                ),
              ],
            ),
          ],
        ),
        LantaiModel(
          id: 'l002',
          name: 'Lantai 2',
          nomorLantai: 2,
          gedungId: 'g001',
          ruangan: [
            RuanganModel(
              id: 'r004',
              name: 'Divisi Marketing',
              lantaiId: 'l002',
              kapasitas: 30,
              tipe: 'Ruang Kerja',
              assets: [
                AssetModel(
                  id: 'a008',
                  name: 'Printer HP LaserJet',
                  category: 'Printer',
                  status: AssetStatus.baik,
                  ruanganId: 'r004',
                  lastMaintenance: DateTime(2025, 3, 20),
                  serialNumber: 'HP-2023-008',
                  brand: 'HP',
                  kondisi: '88%',
                ),
                AssetModel(
                  id: 'a009',
                  name: 'Lampu TL Fluorescent',
                  category: 'Lampu',
                  status: AssetStatus.baik,
                  ruanganId: 'r004',
                  lastMaintenance: DateTime(2025, 1, 15),
                  serialNumber: 'FL-2021-030',
                  brand: 'Osram',
                  kondisi: '92%',
                ),
                AssetModel(
                  id: 'a010',
                  name: 'CCTV Dome Camera',
                  category: 'CCTV',
                  status: AssetStatus.baik,
                  ruanganId: 'r004',
                  lastMaintenance: DateTime(2025, 4, 10),
                  serialNumber: 'CC-2023-005',
                  brand: 'Hikvision',
                  kondisi: '96%',
                ),
              ],
            ),
            RuanganModel(
              id: 'r005',
              name: 'Ruang HR',
              lantaiId: 'l002',
              kapasitas: 15,
              tipe: 'Ruang Kerja',
              assets: [
                AssetModel(
                  id: 'a011',
                  name: 'AC Panasonic 1.5PK',
                  category: 'AC',
                  status: AssetStatus.maintenance,
                  ruanganId: 'r005',
                  lastMaintenance: DateTime(2025, 2, 28),
                  serialNumber: 'PAN-2022-011',
                  brand: 'Panasonic',
                  kondisi: '65%',
                ),
                AssetModel(
                  id: 'a012',
                  name: 'Fingerprint Scanner',
                  category: 'Keamanan',
                  status: AssetStatus.baik,
                  ruanganId: 'r005',
                  lastMaintenance: DateTime(2025, 5, 5),
                  serialNumber: 'FP-2024-002',
                  brand: 'ZKTeco',
                  kondisi: '99%',
                ),
              ],
            ),
          ],
        ),
        LantaiModel(
          id: 'l003',
          name: 'Lantai 3',
          nomorLantai: 3,
          gedungId: 'g001',
          ruangan: [
            RuanganModel(
              id: 'r006',
              name: 'Divisi IT',
              lantaiId: 'l003',
              kapasitas: 25,
              tipe: 'Ruang Kerja',
              assets: [
                AssetModel(
                  id: 'a013',
                  name: 'Server Rack Dell',
                  category: 'Server',
                  status: AssetStatus.baik,
                  ruanganId: 'r006',
                  lastMaintenance: DateTime(2025, 5, 10),
                  serialNumber: 'SRV-2023-001',
                  brand: 'Dell',
                  kondisi: '100%',
                ),
                AssetModel(
                  id: 'a014',
                  name: 'UPS APC 3000VA',
                  category: 'UPS',
                  status: AssetStatus.baik,
                  ruanganId: 'r006',
                  lastMaintenance: DateTime(2025, 4, 20),
                  serialNumber: 'UPS-2024-003',
                  brand: 'APC',
                  kondisi: '95%',
                ),
                AssetModel(
                  id: 'a015',
                  name: 'AC Precision 5PK',
                  category: 'AC',
                  status: AssetStatus.baik,
                  ruanganId: 'r006',
                  lastMaintenance: DateTime(2025, 3, 15),
                  serialNumber: 'ACP-2022-001',
                  brand: 'Stulz',
                  kondisi: '93%',
                ),
              ],
            ),
            RuanganModel(
              id: 'r007',
              name: 'Ruang Meeting C',
              lantaiId: 'l003',
              kapasitas: 12,
              tipe: 'Ruang Rapat',
              assets: [
                AssetModel(
                  id: 'a016',
                  name: 'TV LED 50"',
                  category: 'Smart TV',
                  status: AssetStatus.rusak,
                  ruanganId: 'r007',
                  lastMaintenance: DateTime(2024, 10, 5),
                  serialNumber: 'TV-2021-004',
                  brand: 'LG',
                  kondisi: '30%',
                ),
                AssetModel(
                  id: 'a017',
                  name: 'AC Sharp 2PK',
                  category: 'AC',
                  status: AssetStatus.baik,
                  ruanganId: 'r007',
                  lastMaintenance: DateTime(2025, 2, 10),
                  serialNumber: 'SHP-2023-006',
                  brand: 'Sharp',
                  kondisi: '87%',
                ),
              ],
            ),
          ],
        ),
        LantaiModel(
          id: 'l004',
          name: 'Lantai 4',
          nomorLantai: 4,
          gedungId: 'g001',
          ruangan: [
            RuanganModel(
              id: 'r008',
              name: 'Ruang Direksi',
              lantaiId: 'l004',
              kapasitas: 10,
              tipe: 'Ruang Eksekutif',
              assets: [
                AssetModel(
                  id: 'a018',
                  name: 'AC VRF Daikin',
                  category: 'AC',
                  status: AssetStatus.baik,
                  ruanganId: 'r008',
                  lastMaintenance: DateTime(2025, 5, 1),
                  serialNumber: 'VRF-2024-001',
                  brand: 'Daikin',
                  kondisi: '99%',
                ),
                AssetModel(
                  id: 'a019',
                  name: 'Video Conference Cisco',
                  category: 'Konferensi',
                  status: AssetStatus.baik,
                  ruanganId: 'r008',
                  lastMaintenance: DateTime(2025, 4, 15),
                  serialNumber: 'CIS-2024-001',
                  brand: 'Cisco',
                  kondisi: '97%',
                ),
              ],
            ),
            RuanganModel(
              id: 'r009',
              name: 'Aula Serbaguna',
              lantaiId: 'l004',
              kapasitas: 100,
              tipe: 'Aula',
              assets: [
                AssetModel(
                  id: 'a020',
                  name: 'Sound System Yamaha',
                  category: 'Audio',
                  status: AssetStatus.baik,
                  ruanganId: 'r009',
                  lastMaintenance: DateTime(2025, 3, 5),
                  serialNumber: 'YMH-2023-002',
                  brand: 'Yamaha',
                  kondisi: '90%',
                ),
                AssetModel(
                  id: 'a021',
                  name: 'Proyektor Benq 4K',
                  category: 'Proyektor',
                  status: AssetStatus.baik,
                  ruanganId: 'r009',
                  lastMaintenance: DateTime(2025, 1, 20),
                  serialNumber: 'BNQ-2024-001',
                  brand: 'BenQ',
                  kondisi: '94%',
                ),
                AssetModel(
                  id: 'a022',
                  name: 'AC Central 10PK',
                  category: 'AC',
                  status: AssetStatus.tidakAktif,
                  ruanganId: 'r009',
                  lastMaintenance: DateTime(2024, 8, 10),
                  serialNumber: 'ACN-2019-001',
                  brand: 'York',
                  kondisi: '50%',
                ),
              ],
            ),
          ],
        ),
      ];

  static List<LantaiModel> get _lantaiGedungAnnex => [
        LantaiModel(
          id: 'l005',
          name: 'Lantai 1',
          nomorLantai: 1,
          gedungId: 'g002',
          ruangan: [
            RuanganModel(
              id: 'r010',
              name: 'Gudang Aset',
              lantaiId: 'l005',
              kapasitas: 5,
              tipe: 'Gudang',
              assets: [
                AssetModel(
                  id: 'a023',
                  name: 'Genset Perkins 100KVA',
                  category: 'Genset',
                  status: AssetStatus.baik,
                  ruanganId: 'r010',
                  lastMaintenance: DateTime(2025, 4, 1),
                  serialNumber: 'GNS-2020-001',
                  brand: 'Perkins',
                  kondisi: '88%',
                ),
              ],
            ),
            RuanganModel(
              id: 'r011',
              name: 'Ruang Training',
              lantaiId: 'l005',
              kapasitas: 30,
              tipe: 'Ruang Pelatihan',
              assets: [
                AssetModel(
                  id: 'a024',
                  name: 'Proyektor Epson EB-W52',
                  category: 'Proyektor',
                  status: AssetStatus.baik,
                  ruanganId: 'r011',
                  lastMaintenance: DateTime(2025, 3, 25),
                  serialNumber: 'EPS-2024-008',
                  brand: 'Epson',
                  kondisi: '92%',
                ),
                AssetModel(
                  id: 'a025',
                  name: 'AC Daikin 2PK',
                  category: 'AC',
                  status: AssetStatus.baik,
                  ruanganId: 'r011',
                  lastMaintenance: DateTime(2025, 2, 20),
                  serialNumber: 'DAI-2023-009',
                  brand: 'Daikin',
                  kondisi: '91%',
                ),
              ],
            ),
          ],
        ),
        LantaiModel(
          id: 'l006',
          name: 'Lantai 2',
          nomorLantai: 2,
          gedungId: 'g002',
          ruangan: [
            RuanganModel(
              id: 'r012',
              name: 'Ruang Finance',
              lantaiId: 'l006',
              kapasitas: 20,
              tipe: 'Ruang Kerja',
              assets: [
                AssetModel(
                  id: 'a026',
                  name: 'Brankas Chubb',
                  category: 'Keamanan',
                  status: AssetStatus.baik,
                  ruanganId: 'r012',
                  lastMaintenance: DateTime(2025, 1, 10),
                  serialNumber: 'CHB-2020-001',
                  brand: 'Chubb',
                  kondisi: '100%',
                ),
                AssetModel(
                  id: 'a027',
                  name: 'Printer Epson L3250',
                  category: 'Printer',
                  status: AssetStatus.maintenance,
                  ruanganId: 'r012',
                  lastMaintenance: DateTime(2025, 4, 28),
                  serialNumber: 'EPS-2022-015',
                  brand: 'Epson',
                  kondisi: '60%',
                ),
              ],
            ),
          ],
        ),
      ];

  // ============================================================
  // MAINTENANCE RECORDS
  // ============================================================
  static List<MaintenanceRecord> get maintenanceRecords => [
        MaintenanceRecord(
          id: 'm001',
          assetId: 'a003',
          assetName: 'Smart TV Samsung 55"',
          ruangan: 'Ruang Meeting A',
          lantai: 'Lantai 1',
          gedung: 'Gedung Utama',
          deskripsi: 'Layar berkedip, perlu kalibrasi dan pengecekan panel',
          status: MaintenanceStatus.proses,
          tanggal: DateTime(2025, 5, 15),
          teknisi: 'Rudi Teknisi',
          biaya: 500000,
        ),
        MaintenanceRecord(
          id: 'm002',
          assetId: 'a011',
          assetName: 'AC Panasonic 1.5PK',
          ruangan: 'Ruang HR',
          lantai: 'Lantai 2',
          gedung: 'Gedung Utama',
          deskripsi: 'Freon habis, perlu pengisian ulang dan pembersihan filter',
          status: MaintenanceStatus.menunggu,
          tanggal: DateTime(2025, 5, 18),
          teknisi: 'Budi Teknisi',
          biaya: 350000,
        ),
        MaintenanceRecord(
          id: 'm003',
          assetId: 'a001',
          assetName: 'AC Daikin 2PK',
          ruangan: 'Ruang Meeting A',
          lantai: 'Lantai 1',
          gedung: 'Gedung Utama',
          deskripsi: 'Service rutin 3 bulanan, pembersihan filter dan kondensor',
          status: MaintenanceStatus.selesai,
          tanggal: DateTime(2025, 3, 10),
          teknisi: 'Rudi Teknisi',
          biaya: 200000,
        ),
        MaintenanceRecord(
          id: 'm004',
          assetId: 'a016',
          assetName: 'TV LED 50"',
          ruangan: 'Ruang Meeting C',
          lantai: 'Lantai 3',
          gedung: 'Gedung Utama',
          deskripsi: 'TV mati total, perlu penggantian power supply board',
          status: MaintenanceStatus.menunggu,
          tanggal: DateTime(2025, 5, 20),
          teknisi: 'Belum ditugaskan',
          biaya: 0,
        ),
        MaintenanceRecord(
          id: 'm005',
          assetId: 'a027',
          assetName: 'Printer Epson L3250',
          ruangan: 'Ruang Finance',
          lantai: 'Lantai 2',
          gedung: 'Gedung Annex',
          deskripsi: 'Paper jam, perlu pembersihan roller dan head cleaning',
          status: MaintenanceStatus.proses,
          tanggal: DateTime(2025, 5, 19),
          teknisi: 'Agus Teknisi',
          biaya: 150000,
        ),
        MaintenanceRecord(
          id: 'm006',
          assetId: 'a008',
          assetName: 'Printer HP LaserJet',
          ruangan: 'Divisi Marketing',
          lantai: 'Lantai 2',
          gedung: 'Gedung Utama',
          deskripsi: 'Penggantian toner dan service rutin',
          status: MaintenanceStatus.selesai,
          tanggal: DateTime(2025, 3, 20),
          teknisi: 'Agus Teknisi',
          biaya: 450000,
        ),
      ];

  // ============================================================
  // LAPORAN KERUSAKAN
  // ============================================================
  static List<LaporanKerusakan> get laporanKerusakan => [
        LaporanKerusakan(
          id: 'lk001',
          assetId: 'a007',
          assetName: 'Lampu LED Panel',
          gedungId: 'g001',
          gedungName: 'Gedung Utama',
          nomorLantai: 1,
          lantaiName: 'Lantai 1',
          ruanganId: 'r003',
          ruanganName: 'Lobby Utama',
          deskripsi: 'Lampu mati di sudut kanan lobby, perlu diganti segera',
          pelaporId: 'u002',
          pelaporName: 'Sari Dewi',
          tanggalLapor: DateTime(2025, 5, 16),
          prioritas: 'sedang',
          sudahDitindak: false,
        ),
        LaporanKerusakan(
          id: 'lk002',
          assetId: 'a016',
          assetName: 'TV LED 50"',
          gedungId: 'g001',
          gedungName: 'Gedung Utama',
          nomorLantai: 3,
          lantaiName: 'Lantai 3',
          ruanganId: 'r007',
          ruanganName: 'Ruang Meeting C',
          deskripsi: 'TV tidak bisa dinyalakan, perlu penanganan segera',
          pelaporId: 'u003',
          pelaporName: 'Budi Santoso',
          tanggalLapor: DateTime(2025, 5, 19),
          prioritas: 'tinggi',
          sudahDitindak: true,
        ),
        LaporanKerusakan(
          id: 'lk003',
          assetId: 'a011',
          assetName: 'AC Panasonic 1.5PK',
          gedungId: 'g001',
          gedungName: 'Gedung Utama',
          nomorLantai: 2,
          lantaiName: 'Lantai 2',
          ruanganId: 'r005',
          ruanganName: 'Ruang HR',
          deskripsi: 'AC tidak dingin, ruangan terasa panas sejak pagi',
          pelaporId: 'u002',
          pelaporName: 'Sari Dewi',
          tanggalLapor: DateTime(2025, 5, 18),
          prioritas: 'tinggi',
          sudahDitindak: true,
        ),
        LaporanKerusakan(
          id: 'lk004',
          assetId: 'a003',
          assetName: 'Smart TV Samsung 55"',
          gedungId: 'g001',
          gedungName: 'Gedung Utama',
          nomorLantai: 1,
          lantaiName: 'Lantai 1',
          ruanganId: 'r001',
          ruanganName: 'Ruang Meeting A',
          deskripsi: 'Layar berkedip saat digunakan untuk presentasi',
          pelaporId: 'u003',
          pelaporName: 'Budi Santoso',
          tanggalLapor: DateTime(2025, 5, 14),
          prioritas: 'sedang',
          sudahDitindak: true,
        ),
      ];
}
